explain versioning in readme
nordlb-openapi/actions pull request #2
Opened 2020-12-02 10:50 UTC by manuelottlik

2020-12-02 11:28 UTC, gigo1980 commented on README.md
> +Name des versionierten Branches: `build-docker-image/v1`
An sich funktioniert dies ja erst einmal, was an sich spricht dagegen das über Tags/Releases zu lösen? Ist an sich ja auch nur ein Branch(Referenz)

Was noch zu klären wäre, wie stellt man es mit Semantic Versining an.

Wenn es quasi eine Version 1.2.1 gibt möchte ich ja mit "v1" alle Minor/Patch Versionen mit nutzen und bei "V1.2" auch alle nachfolgenden Patches mitbekommen. Dies könnte ja über eine GitHub Action gelöst werden die dann die Tags ersetzt und korrekt linkt.

2020-12-02 11:31 UTC, manuelottlik commented on README.md
> +Name des versionierten Branches: `build-docker-image/v1`
Stimmt, statt Branches können wir einfach Tags verwenden. Semantic Versioning würde ich erstmal hinten anstellen, bis der Bedarf ist. Wüsste auch nicht, dass die Actions, die GitHub anbietet, das machen.

2020-12-02 11:34 UTC, manuelottlik commented on README.md
> +Name des versionierten Branches: `build-docker-image/v1`
https://github.com/marketplace/actions/actions-tagger

2020-12-02 12:38 UTC, radicarl commented on README.md
> +Name des versionierten Branches: `build-docker-image/v1`
Wir haben die Hoffnung dass wir bald eine nordlb-actions Orga bekommen und dort für jede Action ein eigenes Repo ablegen können. Solange wir diese noch nicht haben, wollen wir nur diese eine Repo verwenden. Deshalb hatten wir uns dafür entschieden, Branches zu verwenden, da wir dadurch die unterschiedlichen Actions von einander unabhängig versionieren können. 

Ginge wahrscheinlich auch mit Tags, nur müsste man dann den Actionnamen immer mit in den Tag einfließen lassen. Bin da leidenschaftslos.

2020-12-08 09:56 UTC, manuelottlik commented on README.md
> +Name des versionierten Branches: `build-docker-image/v1`
Alles klar, ich habs angepasst und spreche jetzt von Tags.

2020-12-08 12:42 UTC, radicarl commented on README.md
> +Name des versionierten Branches: `build-docker-image/v1`
ich würde vielleicht noch erwähnen, das man immer drei Tags pro Version braucht:
xxx/v1
xxx/v1.0
xxx/v1.0.4

wobei erstere mit jeder neuen Minor und jeder neuen Patch-Version neu gesetzt werden müssen, und zweitere bei jeder neuen Patch-Version. Falls das in GitHub möglich ist

2020-12-09 09:14 UTC, radicarl requested changes
ich würde vielleicht noch erwähnen, das man immer drei Tags pro Version braucht:
xxx/v1
xxx/v1.0
xxx/v1.0.4

wobei erstere mit jeder neuen Minor und jeder neuen Patch-Version neu gesetzt werden müssen, und zweitere bei jeder neuen Patch-Version. Falls das in GitHub möglich ist

2020-12-09 10:11 UTC, manuelottlik commented on README.md
> +Name des versionierten Branches: `build-docker-image/v1`
Ja, das ist genau der Actions Tagger, von dem ich da gesprochen habe, der würde das automatisieren. Hab's ergänzt.

2020-12-09 11:47 UTC, radicarl approved these changes
mit der neuen action-orga ist das ja fast schon überflüssig

2020-12-09 11:49 UTC, merged